name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

env:
  build-number-prefix: '1.29'
  
jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - name: Setup Image Variables
        id: setup_image_vars
        run: |
          $VERSION="${{env.build-number-prefix}}.${{github.run_number}}"
          echo "imageVersion=$VERSION" >> "$env:GITHUB_OUTPUT"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet publish -c Release
        
      - name: Tag Code
        uses: mathieudutour/github-tag-action@v6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*
          custom_tag: ${{ steps.setup_image_vars.outputs.imageVersion }}
          
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.setup_image_vars.outputs.imageVersion }}
          files: |
            bin\Release\net8.0\win-x64\publish\EKS-Windows-Bootstrapper.exe
            bin\Release\net8.0\win-x64\publish\Start-EKSBootstrap.ps1
