name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build app
        run: dotnet publish -c Release
        
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin\Release\net8.0\win-x64\publish\EKS-Windows-Bootstrapper.exe
            bin\Release\net8.0\win-x64\publish\Start-EKSBootstrap.ps1
